accounts/urls.py
from django.urls import path

from .views import RegisterView, LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    
    # path("update/", UpdateUserView.as_view(), name="update"),
]

landing/urls.py
from django.urls import path
from .views import LandingPageView

app_name = "landing"


urlpatterns = [
    path("", LandingPageView.as_view(), name="landing_page"),
]

newsletter/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('newsletter/', include('subscriber.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.views import View
from django.shortcuts import render


class LandingPageView(View):

    def get(self, request):
        return render(request, "landing/landing.html")
        

landing/templates/landing/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Newsletter App | Demo Project</title>
        <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js"></script>
        
        <!--====== Favicon Icon ======-->
        <link
            rel="shortcut icon"
            href="{% static 'landing/assets/images/favicon.svg' %}"
            type="image/svg"
        />

        {% comment %} Global CSS {% endcomment %}
        <link rel="stylesheet" href="{% static 'landing/assets/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'landing/assets/css/animate.css' %}" />
        <link rel="stylesheet" href="{% static 'landing/assets/css/lineicons.css' %}" />
        <link rel="stylesheet" href="{% static 'landing/assets/css/ud-styles.css' %}" />
    </head>
    <body>
        {% comment %} Header Section {% endcomment %}
        <header class="ud-header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg mb-5 mt-5">
                            <button class="navbar-toggler">
                                <span class="toggler-icon"> </span>
                                <span class="toggler-icon"> </span>
                                <span class="toggler-icon"> </span>
                            </button>

                            <div class="navbar-collapse">
                                <ul id="nav" class="navbar-nav mx-auto"></ul>
                            </div>

                            <div class="navbar-btn d-none d-sm-inline-block">
                                {% if not request.user.is_authenticated %}
                                    <a href="{% url 'accounts:login' %}" class="ud-main-btn ud-login-btn">
                                        Sign In
                                    </a>
                                    <a href="{% url 'accounts:register' %}" class="ud-main-btn ud-white-btn">
                                        Sign Up
                                    </a>
                                {% else %}
                                    <button 
                                        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                                        hx-post="{% url 'accounts:logout' %}" 
                                        hx-trigger="click"
                                        class="ud-main-btn ud-white-btn"
                                    >
                                        Logout
                                    </button>
                                {% endif %}
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>

        {% comment %} Hero Section {% endcomment %}
        <section class="ud-hero" id="home">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ud-hero-content wow fadeInUp" data-wow-delay=".2s">
                            <h1 class="ud-hero-title">
                                Newsletter App Demo
                            </h1>
                            <p class="ud-hero-desc">
                                A simple demo project that lets you manage multiple newsletters. 
                                Each newsletter includes its own subscription page, subscriber management, 
                                and bulk email sending functionality.
                            </p>
                            <ul class="ud-hero-buttons">
                                <li>
                                    <a href="https://github.com/Minenhle-Ngubane/newsletter" rel="nofollow noopener" target="_blank" class="ud-main-btn ud-white-btn">
                                        View on Github
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="ud-hero-image wow fadeInUp" data-wow-delay=".25s">
                            <img src="{% static 'landing/assets/images/hero/hero-image.png' %}" alt="hero-image" />
                            <img
                                src="{% static 'landing/assets/images/hero/dotted-shape.svg' %}"
                                alt="shape"
                                class="shape shape-1"
                            />
                            <img
                                src="{% static 'landing/assets/images/hero/dotted-shape.svg' %}"
                                alt="shape"
                                class="shape shape-2"
                            />
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {% comment %} Features Section {% endcomment %}
        <section id="features" class="ud-features">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ud-section-title">
                            <h2>Features</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-sm-6">
                        <div class="ud-single-feature wow fadeInUp" data-wow-delay=".1s">
                            <div class="ud-feature-content">
                                <h3 class="ud-feature-title">Authentication</h3>
                                <p class="ud-feature-desc">
                                    - User registration, login, and logout
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-sm-6">
                        <div class="ud-single-feature wow fadeInUp" data-wow-delay=".15s">
                            <div class="ud-feature-content">
                                <h3 class="ud-feature-title">Newsletter Management (CRUD)</h3>
                                <p class="ud-feature-desc">
                                    - Create, read, update, and delete newsletters and subscribers <br><br>
                                    - Responsive Bootstrap-powered forms and layouts
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-sm-6">
                        <div class="ud-single-feature wow fadeInUp" data-wow-delay=".2s">
                            <div class="ud-feature-content">
                                <h3 class="ud-feature-title">Bulk Emails</h3>
                                <p class="ud-feature-desc">
                                    - Send bulk emails to subscribers<br>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-sm-6">
                        <div class="ud-single-feature wow fadeInUp" data-wow-delay=".25s">
                            <div class="ud-feature-content">
                                <h3 class="ud-feature-title">HTMX Integration</h3>
                                <p class="ud-feature-desc">
                                    - Dynamic updates without full page reloads <br><br>
                                    - Partial templates for a smoother UX
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {% comment %} Global JS {% endcomment %}
        <script src="{% static 'landing/assets/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'landing/assets/js/wow.min.js' %}"></script>
        <script src="{% static 'landing/assets/js/main.js' %}"></script>
    </body>
</html>